# Generated by Django 6.0.2 on 2026-02-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physiqyou_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
    ]
