# Generated by Django 6.0.2 on 2026-03-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiqyou_app', '0004_foodlog_workoutlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('met_value', models.FloatField()),
            ],
        ),
    ]
